### ISSUE TITLE
Error: (inverse kinematics) failed to get ik solution

### ISSUE THREAD

**Issue by xiaozhu1697** [HangX-Ma/eleRobotJPS#1]

**Comment by xiaozhu1697** [comment]
1. Open the planning scene
roslaunch elerobot_simple_control elerobot_toplevel_moveit
2. Open JPS Planner
rosrun rokae_jps_navigation rokae_arm_main

When I run the second command , it can emerge some error.
![image](https://github.com/HangX-Ma/eleRobotJPS/assets/58245378/367b2660-0521-49cc-9826-da515bd5254c)
![image](https://github.com/HangX-Ma/eleRobotJPS/assets/58245378/fcfd5620-7601-475e-a3c1-1ccec45e7a2c)
![image](https://github.com/HangX-Ma/eleRobotJPS/assets/58245378/ccbeb7e7-3ff1-4d30-b0bd-9f350b1a9c81)
When I modify the pose of start point accornding to this error information , it can emerge the error (Error: (inverse kinematics) failed to get ik solution )until I press  ctrl c

**Comment by HangX-Ma** [comment]
I also meet such an error if I set an inappropriate start point and end point. The octomap has a strange box alignment strategy that I cannot solve this problem perfectly. Sorry for providing you such an unpleasant experience. I will update the README.md to notify the limitation of JPS and this project. @xiaozhu1697
